FROM golang:1.16.0-alpine

COPY . .

RUN apk update && \
    apk upgrade && \
    apk add --no-cache libc-dev gcc git openssh openssl bash && \
    go mod download && \
    go get -u golang.org/x/lint/golint

WORKDIR /app

RUN go mod download

RUN GOOS=linux GOARCH=amd64 go build -o app

EXPOSE 8080