proxy:
  port: 443
  read_header_timeout: 2000
  shutdown_timeout: 3000
  tls_cert_path: certificates/cert.pem
  tls_key_path: certificates/key.pem
upstreams:
  - host_name: gobel-api.local
    target: http://app:8080
log_level: 0